<?php

namespace AppBundle\Repository;

/**
 * AccionesIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionesIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
