<?php

namespace AppBundle\Repository;

/**
 * AuditoriaUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriaUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
