<?php

namespace AppBundle\Repository;

/**
 * CierreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CierreRepository extends \Doctrine\ORM\EntityRepository
{
}
