<?php

namespace AppBundle\Repository;

/**
 * CierreAuditoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CierreAuditoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
