<?php

namespace AppBundle\Repository;

/**
 * DocumentoLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
