<?php

namespace AppBundle\Repository;

/**
 * HallazgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallazgoRepository extends \Doctrine\ORM\EntityRepository
{
}
