<?php

namespace AppBundle\Repository;

/**
 * IndicadorCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadorCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
