<?php

namespace AppBundle\Repository;

/**
 * MacroPocesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MacroPocesoRepository extends \Doctrine\ORM\EntityRepository
{
}
