<?php

namespace AppBundle\Repository;

/**
 * NormogramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NormogramaRepository extends \Doctrine\ORM\EntityRepository
{
}
