<?php

namespace AppBundle\Repository;

/**
 * ProcedimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
