<?php

namespace AppBundle\Repository;

/**
 * ProcesoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
