<?php

namespace AppBundle\Repository;

/**
 * ProcedimientoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedimientoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
