<?php

namespace AppBundle\Repository;

/**
 * ProcedimientoDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcedimientoDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
