<?php

namespace AppBundle\Repository;

/**
 * RiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiesgoRepository extends \Doctrine\ORM\EntityRepository
{
}
