<?php

namespace AppBundle\Repository;

/**
 * SeguimientoIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
