<?php

namespace AppBundle\Repository;

/**
 * TipoHallazgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHallazgoRepository extends \Doctrine\ORM\EntityRepository
{
}
